### ISSUE TITLE
Implement TryConvertFrom<[i32]> and TryConvertFrom<[BigUint]> for Avec<Avec<u64>>

### ISSUE THREAD

**Issue by Janmajayamall** [gaussian-dev/gauss#11]
Since Avec is much better suited for our purpose it is better to use Avec by default instead of Vec. Lack of implementation of TryConvertFrom<[i32]> and TryConvertFrom<[BigUint]> for Avec<Avec<u64>> is preventing us from using it. Implementation will follow the same playbook as corresponding implementations for Vec<Vec<u64>>

**Comment by nagatoism** [comment]
will do
